version: "3.1"

services:

  web1:
    image: web
    container_name: web1
    build:
       context: .
       dockerfile: ./docker_file/web/dockerfile
    restart: always   

  web2:
    image: web
    container_name: web2
    build:
       context: .
       dockerfile: ./docker_file/web/dockerfile
    restart: always  

  web3:
    image: web
    container_name: web3
    build:
       context: .
       dockerfile: ./docker_file/web/dockerfile
    restart: always  

  haproxy:
    image: haproxy
    container_name: loadbalancer
    bbuild:
       context: .
       dockerfile: ./docker_file/haproxy/dockerfile
    restart: always
    ports:
      - 80:80
    links:
      - "web1"
      - "web2"
      - "web3"
