version: "3.1"

services:

  web1:
    build: .
    dockerfile: WebServer-Dockerfile
    restart: always

  web2:
    build: .
    dockerfile: WebServer-Dockerfile
    restart: always

  web3:
    build: .
    dockerfile: WebServer-Dockerfile
    restart: always

  haproxy:
    build: .
    dockerfile: HAProxy-Dockerfile
    restart: always
    links:
      - "web1"
      - "web2"
      - "web3"
